### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by leeterry** [UnRealDinnerbone/TrampleStopper#3]
Says  this mod needs language provider Javafml:28 or above to load whatever that means. I am using the latest version of forge for 1.14.3 and this mod. Not 100% sure what that means but the other mods work fine and game works after removing this mod form the folder. here is the log if it helps.

[27Jul2019 13:34:37.978] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, lee_terry, --version, 1.14.3-forge-27.0.60, --gameDir, C:\Users\Cliff\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Cliff\AppData\Roaming\.minecraft\assets, --assetIndex, 1.14, --uuid, 16159efda3ae450d8bd0590801d31299, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 27.0.60, --fml.mcVersion, 1.14.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190624.152911]
[27Jul2019 13:34:37.982] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 3.0.2+57+a2bc918 starting: java version 1.8.0_51 by Oracle Corporation
[27Jul2019 13:34:38.160] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[27Jul2019 13:34:38.478] [main/ERROR] [net.minecraftforge.fml.loading.LanguageLoadingProvider/]: Missing language javafml version [28,) wanted by tramplestopper-1.14.3-2.0.0.13-universal.jar, found 27.0
[27Jul2019 13:34:39.164] [pool-2-thread-1/ERROR] [net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler/SCAN]: An error occurred scanning file Mod File: C:\Users\Cliff\AppData\Roaming\.minecraft\mods\tramplestopper-1.14.3-2.0.0.13-universal.jar
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:48) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:144) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler$$Lambda$248/1493988307.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	... 3 more
[27Jul2019 13:34:39.176] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.14.3-forge-27.0.60, --gameDir, C:\Users\Cliff\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Cliff\AppData\Roaming\.minecraft\assets, --username, lee_terry, --assetIndex, 1.14, --uuid, 16159efda3ae450d8bd0590801d31299, --accessToken, ????????, --userType, mojang, --versionType, release]
[27Jul2019 13:34:39.182] [pool-2-thread-1/ERROR] [net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler/SCAN]: An error occurred scanning file Mod File: C:\Users\Cliff\AppData\Roaming\.minecraft\mods\Trapcraft-1.14.2-2.6.0.jar
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:48) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:144) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler$$Lambda$248/1493988307.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	... 3 more
[27Jul2019 13:34:39.189] [pool-2-thread-1/ERROR] [net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler/SCAN]: An error occurred scanning file Mod File: C:\Users\Cliff\AppData\Roaming\.minecraft\mods\TrashSlot_1.14.3-10.4.4.jar
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:48) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:144) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler$$Lambda$248/1493988307.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	... 3 more
[27Jul2019 13:34:39.210] [pool-2-thread-1/ERROR] [net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler/SCAN]: An error occurred scanning file Mod File: C:\Users\Cliff\AppData\Roaming\.minecraft\mods\u_team_core-1.14.3-2.6.1.125.jar
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:48) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:144) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler$$Lambda$248/1493988307.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	... 3 more
[27Jul2019 13:34:39.214] [pool-2-thread-1/ERROR] [net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler/SCAN]: An error occurred scanning file Mod File: C:\Users\Cliff\AppData\Roaming\.minecraft\mods\useful_backpacks-1.14.3-1.7.0.33.jar
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:48) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:144) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler$$Lambda$248/1493988307.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	... 3 more
[27Jul2019 13:34:39.215] [pool-2-thread-1/ERROR] [net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler/SCAN]: An error occurred scanning file Mod File: C:\Users\Cliff\AppData\Roaming\.minecraft\mods\walkthroughberries-1.0.jar
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:48) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:144) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler$$Lambda$248/1493988307.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	... 3 more
[27Jul2019 13:34:39.238] [pool-2-thread-1/ERROR] [net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler/SCAN]: An error occurred scanning file Mod File: C:\Users\Cliff\AppData\Roaming\.minecraft\mods\Xaeros_Minimap_1.17.4_Forge_1.14.3.jar
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:48) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:144) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler$$Lambda$248/1493988307.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	... 3 more
[27Jul2019 13:34:39.254] [pool-2-thread-1/ERROR] [net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler/SCAN]: An error occurred scanning file Mod File: C:\Users\Cliff\AppData\Roaming\.minecraft\mods\XaerosWorldMap_1.4.4_Forge_1.14.3.jar
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:48) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:144) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler$$Lambda$248/1493988307.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	... 3 more
[27Jul2019 13:34:39.444] [pool-2-thread-1/ERROR] [net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler/SCAN]: An error occurred scanning file Mod File: C:\Users\Cliff\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.14.3-27.0.60\forge-1.14.3-27.0.60-universal.jar
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:48) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:144) ~[forge-1.14.3-27.0.60.jar:?]
	at net.minecraftforge.fml.loading.moddiscovery.BackgroundScanHandler$$Lambda$248/1493988307.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	... 3 more
[27Jul2019 13:34:40.646] [Client thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: lee_terry
[27Jul2019 13:34:41.152] [Client thread/INFO] [net.minecraftforge.fml.ModLoader/CORE]: Loading Network data for FML net version: FML2
[27Jul2019 13:34:49.357] [Client thread/WARN] [net.minecraft.client.GameSettings/]: Skipping bad option: lastServer:
[27Jul2019 13:34:49.381] [Client thread/WARN] [net.minecraft.client.GameSettings/]: Skipping bad option: textBackgroundOpacity:
[27Jul2019 13:34:49.398] [Client thread/INFO] [net.minecraft.client.Minecraft/]: LWJGL Version: 3.2.2 build 10
[27Jul2019 13:34:52.911] [Client thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod Loading Exception : fml.language.missingversion [null, VALIDATE, null, javafml, [28,), tramplestopper-1.14.3-2.0.0.13-universal.jar, 27.0]
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:64) ~[?:?]
	at net.minecraftforge.fml.ModLoadingException$$Lambda$453/836170750.apply(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51]
	at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[?:1.8.0_51]
	at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51]
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:113) ~[?:?]
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:122) ~[?:?]
	at net.minecraftforge.fml.ModLoadingStage.<clinit>(ModLoadingStage.java:40) ~[?:?]
	at net.minecraftforge.fml.ModContainer.<init>(ModContainer.java:71) ~[?:?]
	at net.minecraftforge.fml.DefaultModContainers$1.<init>(DefaultModContainers.java:27) ~[?:?]
	at net.minecraftforge.fml.DefaultModContainers.<clinit>(DefaultModContainers.java:26) ~[?:?]
	at net.minecraftforge.fml.ModLoadingContext.getActiveContainer(ModLoadingContext.java:44) ~[?:?]
	at net.minecraftforge.registries.GameData.checkPrefix(GameData.java:947) ~[?:?]
	at net.minecraftforge.registries.ForgeRegistryEntry.setRegistryName(ForgeRegistryEntry.java:45) ~[?:?]
	at net.minecraftforge.registries.ForgeRegistryEntry.setRegistryName(ForgeRegistryEntry.java:50) ~[?:?]
	at net.minecraftforge.registries.ForgeRegistryEntry.setRegistryName(ForgeRegistryEntry.java:32) ~[?:?]
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:54) ~[?:?]
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:65) ~[?:?]
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:34) ~[?:?]
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:230) ~[?:?]
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:226) ~[?:?]
	at net.minecraft.util.SoundEvents.func_219592_a(SoundEvents.java:804) ~[?:?]
	at net.minecraft.util.SoundEvents.<clinit>(SoundEvents.java:7) ~[?:?]
	at net.minecraft.util.registry.Registry.lambda$static$0(Registry.java:78) ~[?:?]
	at net.minecraft.util.registry.Registry$$Lambda$384/2075899560.get(Unknown Source) ~[?:?]
	at net.minecraft.util.registry.Registry.lambda$static$37(Registry.java:247) ~[?:?]
	at net.minecraft.util.registry.Registry$$Lambda$427/52354732.accept(Unknown Source) ~[?:?]
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663) ~[?:1.8.0_51]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:246) ~[?:?]
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:34) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:353) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:154) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.3-27.0.60.jar:27.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$313/766696861.call(Unknown Source) [forge-1.14.3-27.0.60.jar:27.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.0.2.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.0.2.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.0.2.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.0.2.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.0.2.jar:?]
[27Jul2019 13:34:52.918] [Client thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-0.10.3-milestone.0.1+1a5fa31-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:84) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1919/1854983880.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:67) [?:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:453) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:154) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.3-27.0.60.jar:27.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$313/766696861.call(Unknown Source) [forge-1.14.3-27.0.60.jar:27.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.0.2.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.0.2.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.0.2.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.0.2.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.0.2.jar:?]
[27Jul2019 13:34:55.803] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[27Jul2019 13:34:55.899] [Client thread/INFO] [com.mojang.realmsclient.plugin.RealmsPluginImpl/]: Built for minecraft version 1.14.3
[27Jul2019 13:34:57.758] [Server-Worker-3/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event SETUP, 1 errors found.
[27Jul2019 13:34:57.758] [Server-Worker-3/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[27Jul2019 13:34:57.758] [Server-Worker-3/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-0.10.3-milestone.0.1+1a5fa31-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:84) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1919/1854983880.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:92) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:74) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2100/1974786850.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:82) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1919/1854983880.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[27Jul2019 13:35:00.394] [Server-Worker-2/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[27Jul2019 13:35:00.394] [Server-Worker-2/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[27Jul2019 13:35:00.394] [Server-Worker-2/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-0.10.3-milestone.0.1+1a5fa31-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:84) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1919/1854983880.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:105) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:76) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2102/427274463.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[27Jul2019 13:35:00.398] [Client thread/WARN] [net.minecraft.client.GameSettings/]: Skipping bad option: lastServer:
[27Jul2019 13:35:00.399] [Client thread/WARN] [net.minecraft.client.GameSettings/]: Skipping bad option: textBackgroundOpacity:
[27Jul2019 13:35:00.484] [Client thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[27Jul2019 13:35:00.485] [Client thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[27Jul2019 13:35:00.756] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512 textures-atlas
[27Jul2019 13:35:01.490] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256 textures/particle-atlas
[27Jul2019 13:35:01.492] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256 textures/painting-atlas
[27Jul2019 13:35:01.492] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128 textures/mob_effect-atlas

**Comment by UnRealDinnerbone** [comment]
Yha it because that version only supports forge 1.14.4+I forget to change the version on the building of jar there should be a new version soon
